### ISSUE TITLE
建议添加关键字：退订，TD

### ISSUE THREAD

**Issue by mayziran** [metaphilium/PureSMS#1]
同时建议将项目发到酷安的nekosms评论区，需要的话我可以帮忙发

**Comment by Whiskium** [comment]
之所以没有添加诸如「退订」「TD」一类的关键字是因为这样会造成许多误杀。

工信部颁布的《通信短信息服务管理规定》规定了基础电信业务经营者对用户短信息接收意愿核实的责任，即基础电信业务经营者对通过其电信网发送端口类商业性短信息的，应当保证有关用户已经同意或者请求接收有关短信息。因此许多正常短信尾部也会带有「退订」字样，本项目设立的初衷就是为了更人性化地拦截，尽量做到减少误杀，而拦截「退订」可以说几乎能够顶替这个项目 90% 的规则，还能拦截更多（包括垃圾短信与正常短信），因此添加「退订」不适合本项目，恕不收录。

关于发到酷安的事情，使用许可我也写了，分享是没问题的。其实我本人也有酷安的账号，只是酷安的整体素质每况愈下，我不希望引来许多麻烦，所以没有发在那里。
